- name: variables from prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: username
    prompt: what is your username?
    private: false

  tasks:  
  - name: print credentials
    ansible.buitlin.debug:
     msg: "username is: {{ username }}"