- name: Defined variables in Inventory
  hosts: local
  connection: local #Ansible is connecting to localhost
  tasks:
  - name: print the course info
    ansible.builtin.debug:
     msg: "course name is {{COURSE}},duration:{{DURATION}},trainer:{{TRAINER}}"