- name: gather facts
  hosts: local
  connection: local
  # ansible collects the info of target server,before it eexcuets any other fact.
  tasks: 
  - name: facts
    ansible.builtin.debug:
      msg: "{{ ansible_facts }}"