- name: install packages in a loop
  hosts: local
  connection: local 
  tasks: 
  - name: install packages
    ansible.builtin.package: 
      name: "{{ item }}""
      state: present
    loop:
    - nginx
    - mysql
    - zip