- name: install and uninstall packages in a loop
  hosts: local
  connection: local 
  become: true
  tasks: 
  - name: install and remove packages
    ansible.builtin.package: 
      name: "{{ item.name }}"
      state: "{{ item.present }}"
    loop:
    - { name: "nginx", state: "absent" }
    - { name: "mysql", state: "absent" }
    - { name: "zip",   state: "present" }
