- name: convert dictionary to a list
  hosts: local
  connection: local
  vars:
    tags:
      Application: payment
      Environment: dev
  tasks: 
  - name: convert map to list
    ansible.builtin.debug: 
      msg: "Tags are:{{ tags | dict2items }}"