- name: convert  list to a dictionary
  hosts: local
  connection: local
  vars:
    technologies: 
    - key: devops engineer
      value: automate infra
    - key: cloud engineer
      value: build cloud infra   
  tasks: 
  - name: convert  list to a dictionary
    ansible.builtin.debug: 
      msg: "roles: {{ technologies | items2dict }}"

  - name: read student yaml file content and store it in a variable
    ansible.builtin.set_fact: 
      student_fact: "{{ lookup('file', './student.yaml') }}"

  - name: convert yaml file to json
    ansible.builtin.debug:
      msg: "json file : {{ student_fact | to_json }}"   

  - name: copy json into a file
    ansible.builtin.copy:
      content: "{{ student_fact | to_json }}"
      dest: ./student.json
      
    
  