- name: convert  list to a dictionary
  hosts: local
  connection: local
  vars:
    name: "deepthi kattika"
    gmail: Info@GMAIL.com
    ipaddress: 201.125.10.98
    technologies: 
    - key: devops engineer
      value: automate infra
    - key: cloud engineer
      value: build cloud infra   
  tasks: 
  - name: convert  list to a dictionary
    ansible.builtin.debug: 
      msg: "roles: {{ technologies | items2dict }}"

  - name: read student yaml file content and store it in a variable
    ansible.builtin.set_fact: 
      student_fact: "{{ lookup('file', 'student.yaml') | from_yaml }}"

  - name: save JSON formatted data to file
    ansible.builtin.copy: 
      content: "{{ student_fact | to_nice_json }}"
      dest: ./student.json

  - name: convert to uppercase
    ansible.builtin.debug: 
      msg: "name: {{ name | upper }}"    
      
  - name: convert to lowercase
    ansible.builtin.debug: 
      msg: "gmail: {{ gmail | lower }}"     

  - name: check ip valid or not
    ansible.builtin.debug: 
      msg: "ipaddr: {{ ipaddress | ansible.utils.ipv4 }}"     

  - name: find root user in passwd file
    ansible.builtin.shell: cat /etc/passwd | grep root  
    register: command_output

  - name: print the command output
    ansible.builtin.debug:   
      msg: "{{ command_output }}"  

  - name: redirect the command o/p
    ansible.builtin.command: ls -ltr > /tmp/output.txt 
    register: command_output
    ignore_errors: true

  - name: print the command output
    ansible.builtin.debug:   
      msg: "{{ command_output }}"      

  - name: redirect the command o/p
    ansible.builtin.shell: ls -ltr > /tmp/output.txt #If the file doesn’t exist, it is created automatically
    register: command_output

  - name: print the command output
    ansible.builtin.debug:   
      msg: "{{ command_output }}"      

  - name: redirect the command o/p
    ansible.builtin.command: ls -ltr 
    register: command_output

  - name: print the command output
    ansible.builtin.debug:   
      msg: "{{ command_output }}"  
          
    
  