- name: convert  list to a dictionary
  hosts: local
  connection: local
  vars:
    technologies: 
    - key: devops engineer
      value: automate infra
    - key: cloud engineer
      value: build cloud infra   
  tasks: 
  - name: convert  list to a dictionary
    ansible.builtin.debug: 
      msg: "roles: {{ technologies | items2dict }}"
    
