- name : check user
  hosts: local
  connection: local
  become: true
  tasks: 
  - name: check user
    ansible.builtin.command: id roboshop
    register: command_output
    ignore_errors: true
    
  - name: print the output
    ansible.builtin.debug:
    msg: "{{ command_output }}"